### ISSUE TITLE
backend kaatuu reitillä /saaasemat/:id

### ISSUE THREAD

**Issue by jmkahko** [jmkahko/saajuna-backend#16]
Jos tulee muu kuin :id arvo, niin aiheutuu virhe ja backend kaatuu

http://localhost:3000/saaasemat/gv3rgvvbefbvdf

 404 6.804 ms - 2058
node:events:346
      throw er; // Unhandled 'error' event
      ^

CastError: Cast to ObjectId failed for value "gv3rgvvbefbvdf" at path "_id" for model "Havaintoasema"

**Comment by leenakahko** [comment]
Tehty virheenkorjausta ja backend ei kaadu enää tähän virheeseen.
