### ISSUE TITLE
Backend kaatuu reitillä /saaasemat/:fmisid

### ISSUE THREAD

**Issue by jmkahko** [jmkahko/saajuna-backend#17]
Aiheuttaa virhe ilmoituksen ja kaatuu

GET /saaasemat/ 304 294.055 ms - -
node:events:346
      throw er; // Unhandled 'error' event
      ^

CastError: Cast to ObjectId failed for value "101528" at path "_id" for model "Havaintoasema"

Onkohan tämä reitti ihan turha? Jos on niin poistaa reitti käytöstä

**Comment by leenakahko** [comment]
Tehty virheenkorjausta ja korjattu ettei backend kaadu enää tähän.
