### ISSUE TITLE
backend kaatuu reitillä /saaasemat/saanyt/:fmisid

### ISSUE THREAD

**Issue by jmkahko** [jmkahko/saajuna-backend#18]
Jos fmisid numero ei ole  oikea, niin tulee virhe ilmoitus ja backend kaatuu

node:events:346
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'time' of null

**Comment by leenakahko** [comment]
Korjattu ajan haun koodausta seuraavasti.

  let erotus;
        if (!error) {
          //jos ajanhaussa ei tule virhettä, lasketaan erotus normaalisti
          erotus =
            new Date(kellonaika.time).getTime() - new Date(aika).getTime();
        } else {
          console.log(error); // jos ajanhaussa tulee virhe, tulostetaan virhe.
