### ISSUE TITLE
havaintoasemacontroller.js haeHavaintoasemanSaa ajantarkistus

### ISSUE THREAD

**Issue by jmkahko** [jmkahko/saajuna-backend#8]
Tällä hetkellä ajan tarkistuksessa palautuva luku on muu kuin 180, niin tallennetaan säätiedot tietokantaan.
Tarkistaa tilanne, kun aikaa on kulunut tunti tai/ja päivä, miten haku toimii, kun tietokannasta saatu aika ja nykyisen ajan erotus on isompi

**Comment by leenakahko** [comment]
Tämä toimii nykyisellä toiminnallisuudella. Suljetaan issue.
